[project]
name = "papermaker"
version = "0.1.0"
description = "Add a short description here"
authors = ["mdaeron <mathieu@daeron.fr>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
clean = "rm -f tex/input/* || echo; rm -f tmp/* || echo; "
maketitle = "python maketitle.py"
makeabstract = "pandoc src/abstract.md -o tex/input/abstract.tex"
makefloats = "python makefloats.py"
makebody = "pandoc tmp/body_withfloats.md -o tex/input/body.tex"
makeack = "pandoc src/acknowledgements.md -o tex/input/acknowledgements.tex || echo No acknowledgements found"
makecontrib = "pandoc src/contributions.md -o tex/input/contributions.tex || echo No contributions found"
makerepro = "pandoc src/reproducibility.md -o tex/input/reproducibility.tex || echo No reproducibility found"
makebib = "cp src/refs.bib tex/input/refs.bib"
pandoc = { depends_on = ["makeabstract", "makecontrib", "makeack", "makerepro", "makebody"] }
makepdf = { cmd = 'xelatex main.tex; biber main; xelatex main.tex', depends_on = ["clean", "maketitle", "makefloats", "makebib", "pandoc"], cwd = 'tex' }
build = { cmd = 'cp tex/main.pdf build/paper.pdf', depends_on = ["makepdf"]}

[dependencies]
pandoc = ">=3.1.3,<3.2"
python = ">=3.12.1,<3.13"
