[project]
name = "papermaker"
version = "0.1.0"
description = "Add a short description here"
authors = ["mdaeron <mathieu@daeron.fr>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
clean = "rm -f tex/input/* || echo; rm -f tmp/* || echo; "
maketitle = "python maketitle.py"
makeabstract = "pandoc src/abstract.md -o tex/input/abstract.tex"
makefloats = "python makefloats.py"
makebody = "pandoc tmp/body_withfloats.md -o tex/input/body.tex"
makeack = "pandoc src/acknowledgements.md -o tex/input/acknowledgements.tex || echo acknowledgements.md not found"
makecontrib = "pandoc src/contributions.md -o tex/input/contributions.tex || echo contributions.md not found"
makerepro = "pandoc src/reproducibility.md -o tex/input/reproducibility.tex || echo reproducibility.md not found"
copybib = "cp src/refs.bib tex/input/refs.bib"
copypreamble = "cp src/preamble.tex tex/input/preamble.tex || echo preamble.tex not found"
pandoc = { depends_on = ["makeabstract", "makecontrib", "makeack", "makerepro", "makebody"] }
oldbuild = { cmd = 'cp tex/article.pdf build/paper.pdf', depends_on = ["makepdf"]}

[tasks.makepdf]
cmd = 'python ../makepdf.py'
depends_on = ["clean", "maketitle", "makefloats", "copybib", "copypreamble", "pandoc"]
cwd = 'tex'

[tasks.build]
cmd = 'python papermaker.py'

[dependencies]
pandoc = ">=3.1.3,<3.2"
python = ">=3.12.1,<3.13"
