title = 'Papermaker: an attempt at frictionless typesetting of publication-ready scientific articles'

[[author]]
name = 'M. Daëron'
affiliations = 'LSCE'
email = 'daeron@lsce.ipsl.fr'
orcid = '0000-0003-1210-9786'
corresponding = true

[[author]]
name = 'K. Malone'
affiliations = ['DMPC']
email = 'kevin@dmpc.com'

[[author]]
name = 'P. M. Beesly-Halpert'
affiliations = ['DMPC', 'MSPC']
email = 'pam@dmpc.com'

[[author]]
name = 'M. G. Scott'
affiliations = ['DMPC', 'MSPC']
email = 'micheal@mspc.com'
# corresponding = true

[affiliations]
LSCE = "Laboratoire des Sciences du Climat et de l'Environnement"
DMPC = "Dunder Mifflin Paper Company"
MSPC = "Michael Scott Paper Company"
